name: PlannerAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎️
      uses: actions/checkout@v2

      - name: Change directory into PlannerAPI
      run: cd PlannerAPI

      


