name: PlannerAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code 🛎️
      uses: actions/checkout@v2

      - name: Change directory into PlannerAPI
      run: cd PlannerAPI

      - name: Setup .NET 6 🔧
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'




